MAIN_MD := assignment_2.md

INSERT_MD := ../common/brainstorm.md
INSERT_MD += ../common/morphological_chart.md
INSERT_MD += ../common/decision_table.md
INSERT_MD += ../common/gantt.md
INSERT_MD += ../common/need_statement.md
INSERT_MD += ../common/goal_statement.md

include ../pdf.mk
