MAIN_MD := assignment_2.md

INSERT_MD := ../common/brainstorm.md
INSERT_MD += ../common/Morphology_Table.md
INSERT_MD += ../common/decision_table.md
INSERT_MD += ../common/gantt.md

include ../pdf.mk
