MAIN_MD := assignment_1.md

INSERT_TEX := ../common/need_statement.tex
INSERT_TEX += ../common/goal_statement.tex
INSERT_TEX += ../common/design_objective_table.tex
INSERT_TEX += ../common/design_objective.tex
INSERT_TEX += ../common/personas.tex

include ../pdf.mk
