MAIN_MD := assignment_1.md

INSERT_TEX := ../common/need_statement.tex
INSERT_TEX += ../common/goal_statement.tex
INSERT_TEX += ../common/design_objective_table.tex

INSERT_MD += ../common/design_objective.md
INSERT_MD := ../common/personas.md
INSERT_MD += ../common/personas/camillia.md
INSERT_MD += ../common/personas/elijah.md
INSERT_MD += ../common/personas/linda.md
INSERT_MD += ../common/personas/mary.md
INSERT_MD += ../common/personas/peyton.md

include ../pdf.mk
