MAIN_MD := assignment_1.md

INSERT_MD := ../common/need_statement.md
INSERT_MD += ../common/goal_statement.md
INSERT_MD += ../common/design_objective_table.md
INSERT_MD += ../common/design_objective.md
INSERT_MD += ../common/personas.md
INSERT_MD += ../common/personas/camillia.md
INSERT_MD += ../common/personas/elijah.md
INSERT_MD += ../common/personas/linda.md
INSERT_MD += ../common/personas/mary.md
INSERT_MD += ../common/personas/peyton.md

include ../pdf.mk
