version: "3"

services:
    app:
        build:
            context: flask
            dockerfile: Dockerfile
        env_file: flask/.env
        container_name: app
        networks:
            - app-network

    caddy:
        build:
            context: caddy
            dockerfile: Dockerfile
        container_name: caddy
        ports:
            - 80:80
            - 443:443
        networks:
            - app-network
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - app

networks:
    app-network:

volumes:
    caddy_data:
    caddy_config:
