MAIN_MD := assignment_3.md

INSERT_MD := ../common/design_for_manufacture_and_assembly.md
INSERT_MD += ../common/ethics_statement.md
INSERT_MD += ../common/prototype_budget.md
INSERT_MD += ../common/lifecycle_assessment.md
INSERT_MD += ../common/test_plan.md

include ../pdf.mk
